@extends('layouts.default')
@section('content')

    {{ HTML::style('css/about.css'); }}
    {{ HTML::script('script/about.js'); }}

	<div class="body-wrapper container">
	<div class="row">
		<!-- <div class="col-sm-1"> -->
		<ul id="tabs">
		  <li><a href="#mission">Mission & Vision</a></li> 
		  <li><a href="#timeline">Timeline</a></li>
		  <li><a href="#about">About Us</a></li>
		</ul>

	<div class="content-wrapper container">
		<div class="tabContent" id="about">
		  <h2 class="content-header">About Us</h2>
		    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tristique velit vitae interdum blandit. Aliquam eu convallis turpis. Curabitur non neque hendrerit, maximus tortor non, tincidunt risus. Vivamus volutpat urna vel magna iaculis, vel fringilla risus suscipit. Vivamus in varius leo, at tempor eros. Nulla velit est, iaculis ut nibh non, pretium tempus ligula. Duis ipsum nisl, dictum et lectus a, commodo pulvinar neque. Suspendisse mattis velit tempus dictum vestibulum. Sed nibh ante, molestie in semper ac, tristique et lacus. Suspendisse eleifend accumsan enim, varius vehicula ex. Praesent eleifend, mi sed accumsan fringilla, metus massa ultrices nibh, ut mollis odio nisi et est. Aliquam aliquet suscipit ornare.</p>
			<p>About about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about about</p>
			<p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent quis arcu fringilla, eleifend lacus quis, accumsan nunc. Vestibulum sapien nulla, laoreet sed pellentesque sit amet, scelerisque vitae nisi. Praesent nisi nulla, aliquet eget erat vitae, convallis imperdiet felis. Etiam lacinia mi nec orci euismod, eget lobortis dolor interdum. Vivamus lacus odio, malesuada at convallis eu, elementum vitae eros. Suspendisse scelerisque justo faucibus, euismod nunc ultrices, fermentum lectus. Maecenas blandit pellentesque turpis, eget ullamcorper justo porta at. Maecenas ac mi sit amet orci tempor ultricies.</p>
			<p>Ut consequat consequat ante, ut sagittis turpis vestibulum vel. Etiam porta, metus sed convallis eleifend, orci eros elementum quam, eu aliquet nulla nunc sed nisi. Cras risus sem, tincidunt ac pharetra convallis, porttitor a nunc. Etiam arcu purus, tristique sit amet nunc quis, tincidunt eleifend purus. Phasellus iaculis eu risus ac pretium. Proin sit amet posuere ligula, at rutrum purus. Cras eget dui sed dolor eleifend ullamcorper. Mauris lectus leo, tempus nec gravida a, sodales ac arcu. Maecenas dictum turpis et magna ultricies pharetra. Proin pretium, elit vitae cursus accumsan, lacus ligula lobortis justo, ut vulputate lectus dui a turpis.</p>
			<p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent quis arcu fringilla, eleifend lacus quis, accumsan nunc. Vestibulum sapien nulla, laoreet sed pellentesque sit amet, scelerisque vitae nisi. Praesent nisi nulla, aliquet eget erat vitae, convallis imperdiet felis. Etiam lacinia mi nec orci euismod, eget lobortis dolor interdum. Vivamus lacus odio, malesuada at convallis eu, elementum vitae eros. Suspendisse scelerisque justo faucibus, euismod nunc ultrices, fermentum lectus. Maecenas blandit pellentesque turpis, eget ullamcorper justo porta at. Maecenas ac mi sit amet orci tempor ultricies.</p>
		</div>

		<div class="tabContent" id="timeline">
		<div id="side">
			<p>ICS THROUGH THE YEARS</p>
		</div>
		<div id="content">
		  <h2 class="content-header">Timeline</h2>
		    <p id="part">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tristique velit vitae interdum blandit. Aliquam eu convallis turpis. Curabitur non neque hendrerit, maximus tortor non, tincidunt risus. Vivamus volutpat urna vel magna iaculis, vel fringilla risus suscipit. Vivamus in varius leo, at tempor eros. Nulla velit est, iaculis ut nibh non, pretium tempus ligula. Duis ipsum nisl, dictum et lectus a, commodo pulvinar neque. Suspendisse mattis velit tempus dictum vestibulum. Sed nibh ante, molestie in semper ac, tristique et lacus. Suspendisse eleifend accumsan enim, varius vehicula ex. Praesent eleifend, mi sed accumsan fringilla, metus massa ultrices nibh, ut mollis odio nisi et est. Aliquam aliquet suscipit ornare. <br />Ut consequat consequat ante, ut sagittis turpis vestibulum vel. Etiam porta, metus sed convallis eleifend, orci eros elementum quam, eu aliquet nulla nunc sed nisi. Cras risus sem, tincidunt ac pharetra convallis, porttitor a nunc. Etiam arcu purus, tristique sit amet nunc quis, tincidunt eleifend purus. Phasellus iaculis eu risus ac pretium. Proin sit amet posuere ligula, at rutrum purus. Cras eget dui sed dolor eleifend ullamcorper. Mauris lectus leo, tempus nec gravida a, sodales ac arcu. Maecenas dictum turpis et magna ultricies pharetra. Proin pretium, elit vitae cursus accumsan, lacus ligula lobortis justo, ut vulputate lectus dui a turpis.</p>
			<p id="part">Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent quis arcu fringilla, eleifend lacus quis, accumsan nunc. Vestibulum sapien nulla, laoreet sed pellentesque sit amet, scelerisque vitae nisi. Praesent nisi nulla, aliquet eget erat vitae, convallis imperdiet felis. Etiam lacinia mi nec orci euismod, eget lobortis dolor interdum. Vivamus lacus odio, malesuada at convallis eu, elementum vitae eros. Suspendisse scelerisque justo faucibus, euismod nunc ultrices, fermentum lectus. Maecenas blandit pellentesque turpis, eget ullamcorper justo porta at. Maecenas ac mi sit amet orci tempor ultricies.</p>
			<p id="part">Ut consequat consequat ante, ut sagittis turpis vestibulum vel. Etiam porta, metus sed convallis eleifend, orci eros elementum quam, eu aliquet nulla nunc sed nisi. Cras risus sem, tincidunt ac pharetra convallis, porttitor a nunc. Etiam arcu purus, tristique sit amet nunc quis, tincidunt eleifend purus. Phasellus iaculis eu risus ac pretium. Proin sit amet posuere ligula, at rutrum purus. Cras eget dui sed dolor eleifend ullamcorper. Mauris lectus leo, tempus nec gravida a, sodales ac arcu. Maecenas dictum turpis et magna ultricies pharetra. Proin pretium, elit vitae cursus accumsan, lacus ligula lobortis justo, ut vulputate lectus dui a turpis.<br />Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent quis arcu fringilla, eleifend lacus quis, accumsan nunc. Vestibulum sapien nulla, laoreet sed pellentesque sit amet, scelerisque vitae nisi. Praesent nisi nulla, aliquet eget erat vitae, convallis imperdiet felis. Etiam lacinia mi nec orci euismod, eget lobortis dolor interdum. Vivamus lacus odio, malesuada at convallis eu, elementum vitae eros. Suspendisse scelerisque justo faucibus, euismod nunc ultrices, fermentum lectus. Maecenas blandit pellentesque turpis, eget ullamcorper justo porta at. Maecenas ac mi sit amet orci tempor ultricies.</p>
		</div>
	</div>

		<div class="tabContent" id="mission">
		  <h2 class="content-header">Mission & Vision</h2>
		    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tristique velit vitae interdum blandit. Aliquam eu convallis turpis. Curabitur non neque hendrerit, maximus tortor non, tincidunt risus. Vivamus volutpat urna vel magna iaculis, vel fringilla risus suscipit. Vivamus in varius leo, at tempor eros. Nulla velit est, iaculis ut nibh non, pretium tempus ligula. Duis ipsum nisl, dictum et lectus a, commodo pulvinar neque. Suspendisse mattis velit tempus dictum vestibulum. Sed nibh ante, molestie in semper ac, tristique et lacus. Suspendisse eleifend accumsan enim, varius vehicula ex. Praesent eleifend, mi sed accumsan fringilla, metus massa ultrices nibh, ut mollis odio nisi et est. Aliquam aliquet suscipit ornare.</p>
			<p>Ut consequat consequat ante, ut sagittis turpis vestibulum vel. Etiam porta, metus sed convallis eleifend, orci eros elementum quam, eu aliquet nulla nunc sed nisi. Cras risus sem, tincidunt ac pharetra convallis, porttitor a nunc. Etiam arcu purus, tristique sit amet nunc quis, tincidunt eleifend purus. Phasellus iaculis eu risus ac pretium. Proin sit amet posuere ligula, at rutrum purus. Cras eget dui sed dolor eleifend ullamcorper. Mauris lectus leo, tempus nec gravida a, sodales ac arcu. Maecenas dictum turpis et magna ultricies pharetra. Proin pretium, elit vitae cursus accumsan, lacus ligula lobortis justo, ut vulputate lectus dui a turpis.</p>
			<p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent quis arcu fringilla, eleifend lacus quis, accumsan nunc. Vestibulum sapien nulla, laoreet sed pellentesque sit amet, scelerisque vitae nisi. Praesent nisi nulla, aliquet eget erat vitae, convallis imperdiet felis. Etiam lacinia mi nec orci euismod, eget lobortis dolor interdum. Vivamus lacus odio, malesuada at convallis eu, elementum vitae eros. Suspendisse scelerisque justo faucibus, euismod nunc ultrices, fermentum lectus. Maecenas blandit pellentesque turpis, eget ullamcorper justo porta at. Maecenas ac mi sit amet orci tempor ultricies.</p>
		</div>

	</div>
	</div>
	</div>
@stop